FROM ubuntu
RUN apt-get update \
    && apt-get install -y python3 \
    && apt-get install -y python3-dev \
    && apt-get install -y python3-pip \
    && pip3 install tornado \
    && rm -rf /var/lib/apt/lists/*
